name: trashvisor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  dio: ^5.5.0 # http
  path: ^1.8.3 # path
  http: ^1.1.0 # untuk mengirimkan permintaan HTTP ke APi
  flutter_dotenv: ^6.0.0 # untuk menyimpan API key dengan aman
  flutter_markdown: ^0.7.0
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.0 # supabase import
  shared_preferences: ^2.2.2 # shared preferences
  # flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  intl: ^0.19.0
  another_flushbar: ^1.10.28
  timeago: ^3.7.0
  app_links: ^6.2.0
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_apk.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/images/bg/
    - assets/images/onboarding/
    - assets/images/sponsors/
    - assets/images/login_and_register/
    - assets/images/home_and_profile/
    - assets/images/features/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-ExtraBold.ttf
          weight: 800
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800